controller_list:
  - name: panda_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - franka_arm_joint1
      - franka_arm_joint2
      - franka_arm_joint3
      - franka_arm_joint4
      - franka_arm_joint5
      - franka_arm_joint6
      - franka_arm_joint7
  - name: panda_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - franka_arm_finger_joint1
      - franka_arm_finger_joint2