# Default initial positions for omtp_factory's ros2_control fake system

initial_positions:
  panda1_finger_joint1: 0
  panda1_finger_joint2: 0
  panda1_joint1: 0.0
  panda1_joint2: -0.785
  panda1_joint3: 0.0
  panda1_joint4: -2.356
  panda1_joint5: 0.0
  panda1_joint6: 1.571
  panda1_joint7: 0.785