# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    panda_1_controller:
      type: joint_trajectory_controller/JointTrajectoryController



    panda_1_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

panda_1_controller:
  ros__parameters:
    open_loop_control: false
    constraints:
      stopped_velocity_tolerance: 0.25
      goal_time: 0.6
    command_interfaces:
      - position
      # - velocity
      # - effort
    state_interfaces:
      - position
      - velocity
      # - acceleration
      # - effort
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    gains:
      panda_joint1:
        angle_wraparound: false
        d: 150.0
        ff_velocity_scale: 1.0
        i: 1.0
        i_clamp: 1.0
        p: 30000.0
      panda_joint2:
        angle_wraparound: false
        d: 100.0
        ff_velocity_scale: 1.0
        i: 1.0
        i_clamp: 1.0
        p: 23000.0
      panda_joint3:
        angle_wraparound: false
        d: 100.0
        ff_velocity_scale: 1.0
        i: 1.0
        i_clamp: 1.0
        p: 20000.0
      panda_joint4:
        angle_wraparound: false
        d: 100.0
        ff_velocity_scale: 1.0
        i: 1.0
        i_clamp: 1.0
        p: 18000.0
      panda_joint5:
        angle_wraparound: false
        d: 100.0
        ff_velocity_scale: 1.0
        i: 1.0
        i_clamp: 1.0
        p: 12000.0
      panda_joint6:
        angle_wraparound: false
        d: 100.0
        ff_velocity_scale: 1.0
        i: 1.0
        i_clamp: 1.0
        p: 10000.0
      panda_joint7:
        angle_wraparound: false
        d: 100.0
        ff_velocity_scale: 1.0
        i: 1.0
        i_clamp: 1.0
        p: 8000.0

panda_1_gripper_controller:
  ros__parameters:
    open_loop_control: false
    joints:
      - panda_finger_joint1
      - panda_finger_joint2
    command_interfaces:
      - position
      # - velocity
      # - effort
    state_interfaces:
      - position
      - velocity
      # - acceleration
      # - effort
    gains:
      panda_finger_joint1:
          angle_wraparound: false
          d: 10.0
          ff_velocity_scale: 10.0
          i: 10.0
          i_clamp: 10.0
          p: 100.0
      panda_finger_joint2:
          angle_wraparound: false
          d: 10.0
          ff_velocity_scale: 10.0
          i: 10.0
          i_clamp: 10.0
          p: 100.0


          # p = 18000
          # d = 100
          # I = 1
          # i clamp = 1

          # arm controller
            # constarins goal_time 0.6
            # stopped velocity_tolerance: 0.05